docmost_base_path: "{{ base_app_storage_path }}/docmost"
docmost_data: "{{ docmost_base_path }}/data"

docmost_db_path: "{{ base_local_ssd_storage_path }}/docmost"
docmost_db_backups_sripts: "{{ docmost_db_path }}/db_backups_scripts"
docmost_db: "{{ docmost_db_path }}/db"
docmost_redis: "{{ docmost_db_path }}/redis"

docmost_db_name: "{{ vm_username }}"
docmost_db_user: "{{ vm_username }}"
docmost_db_password: "{{ db_password }}"
docmost_domain: "docmost.{{ subdomain }}"

docmost_port: 3000

docmost_app_secret: "{{ complex_db_secret }}"

docmost_backup_db: false
docmost_restore_db: false
