---
immich_version: "release"
immich_external_library_path: "{{ my_cloud_nas_storage_path }}"
upload_location: "{{ immich_external_library_path }}/Immich"

immich_external_non_cloud_path: "{{ my_non_cloud_nas_storage_path }}/immich_thumbs"
immich_thumbs_dir: "{{ immich_external_non_cloud_path }}/thumbs"
immich_encoded_video_dir: "{{ immich_external_non_cloud_path }}/encoded_videos"

immich_base_path: "{{ base_local_ssd_storage_path }}/immich"
db_data_location: "{{ immich_base_path }}/dbdata"
immich_compose_dir: "{{ immich_base_path }}/compose"
immich_tmp_dir: "{{ immich_base_path }}/tmp"

immich_cloud_base_path: "{{ base_app_storage_path }}/immich"

immich_db_username: "{{ vm_username }}"
immich_db_password: "{{ db_password }}"
immich_db_name: "{{ vm_username }}"

immich_domain: "immich.{{ subdomain }}"

immich_backup_db: false
immich_restore_db: false
