
media_config_nas_base_path: "{{ base_app_storage_path }}/media"
media_data_path: "{{ my_non_cloud_nas_storage_path }}/Media"
media_config_local_path: "{{ base_local_ssd_storage_path }}/Media"

# Jellyfin
jellyfin_base_path: "{{ media_config_nas_base_path }}/jellyfin"
jellyfin_config: "{{ jellyfin_base_path }}/config"

jellyfin_local_ssd_path: "{{ media_config_local_path }}/jellyfin"
jellyfin_cache: "{{ jellyfin_local_ssd_path }}/cache"
jellyfin_logs: "{{ jellyfin_local_ssd_path }}/logs"
jellyfin_metadata: "{{ jellyfin_local_ssd_path }}/metadata"

# Sonarr
sonarr_base_path: "{{ media_config_nas_base_path }}/sonarr"
sonarr_config: "{{ sonarr_base_path }}/config"

sonarr_local_ssd_path: "{{ media_config_local_path }}/sonarr"
sonarr_logs: "{{ sonarr_local_ssd_path }}/logs"
sonarr_metadata: "{{ sonarr_local_ssd_path }}/MediaCover"

# Radarr
radarr_base_path: "{{ media_config_nas_base_path }}/radarr"
radarr_config: "{{ radarr_base_path }}/config"

radarr_local_ssd_path: "{{ media_config_local_path }}/radarr"
radarr_logs: "{{ radarr_local_ssd_path }}/logs"
radarr_metadata: "{{ radarr_local_ssd_path }}/MediaCover"

# Prowlarr
prowlarr_base_path: "{{ media_config_nas_base_path }}/prowlarr"
prowlarr_config: "{{ prowlarr_base_path }}/config"

prowlarr_local_ssd_path: "{{ media_config_local_path }}/prowlarr"
prowlarr_logs: "{{ prowlarr_local_ssd_path }}/logs"

# qBittorrent
qbittorrent_base_path: "{{ media_config_nas_base_path }}/qbittorrent"
qbittorrent_config: "{{ media_config_nas_base_path }}/qbittorrent"

# NZBGet
nzbget_base_path: "{{ media_config_nas_base_path }}/nzbget"
nzbget_config: "{{ nzbget_base_path }}/config"

nzbget_username: "{{ vm_username }}"
nzbget_password: "{{ vm_password }}"

# Aria2 Pro
aria2_pro_base_path: "{{ media_config_nas_base_path }}/aria2_pro"
aria2_pro_config: "{{ aria2_pro_base_path }}/config"

aria2_pro_secret: "{{ vm_password }}"

# Jellyseerr
jellyseerr_base_path: "{{ media_config_nas_base_path }}/jellyseerr"
jellyseerr_config: "{{ jellyseerr_base_path }}/config"

jellyseerr_local_ssd_path: "{{ media_config_local_path }}/jellyseerr"
jellyseerr_cache: "{{ jellyseerr_local_ssd_path }}/cache"
jellyseerr_logs: "{{ jellyseerr_local_ssd_path }}/logs"

# Jellystat
jellystat_base_path: "{{ media_config_nas_base_path }}/jellystat"
jellystat_db_backups: "{{ jellystat_base_path }}/backups"

jellystat_local_ssd_path: "{{ media_config_local_path }}/jellystat"
jellystat_db_data: "{{ jellystat_local_ssd_path }}/db"

jellystat_db_username: "{{ vm_username }}"
jellystat_db_password: "{{ vm_password }}"
jellystat_jwt_key: "{{ vm_password }}"



aria_domain: "aria.{{ subdomain }}"
flaresolverr_domain: "flaresolverr.{{ subdomain }}"
jellyfin_domain: "jellyfin.{{ subdomain }}"
jellyseerr_domain: "jellyseerr.{{ subdomain }}"
jellystat_domain: "jellystat.{{ subdomain }}"
lunasea_domain: "lunasea.{{ subdomain }}"
nzbget_domain: "nzbget.{{ subdomain }}"
prowlarr_domain: "prowlarr.{{ subdomain }}"
qbittorrent_domain: "qbittorrent.{{ subdomain }}"
radarr_domain: "radarr.{{ subdomain }}"
sonarr_domain: "sonarr.{{ subdomain }}"


