cron_nas_all_apps_path: "{{ base_app_storage_path }}"
cron_nas_base_path: "{{ cron_nas_all_apps_path }}/cron"
cron_nase_base_crontab_file: "{{ cron_nas_base_path }}/cronfile"

cron_local_base_path: "{{ base_local_ssd_storage_path }}/cron"
cron_local_scripts_path: "{{ cron_local_base_path }}/scripts"



matrix_url_l: "{{ matrix_url }}"
matrix_user_id_l: "{{ matrix_user_id }}"
matrix_access_token_l: "{{ matrix_access_token }}"
matrix_room_id_l: "{{ matrix_room_id }}"



