rclone_nas_storage_path: "{{ my_cloud_nas_storage_path }}"
rclone_nas_app_storage_path: "{{ my_cloud_nas_app_storage_path }}"

rclone_base_path: "{{ base_local_ssd_storage_path }}/rclone"

rclone_config_path: "{{ rclone_base_path }}/config"
rclone_sync_script_path: "{{ rclone_base_path }}/sync_script"

rclone_log_path: "{{ rclone_base_path }}/log"
rclone_cache_path: "{{ rclone_base_path }}/cache"
rclone_data_path: "{{ rclone_base_path }}/data"
rclone_google_drive_mount_path: "{{ rclone_data_path }}/GoogleDrive"
rclone_pcloud_mount_path: "{{ rclone_data_path }}/pCloud"

rclone_username: "{{ vm_username }}"
rclone_password: "{{ vm_password }}"

rclone_domain: "rclone.{{ subdomain }}"

google_drive_access_token: "{{ shajal_google_drive_access_token }}"
google_drive_refresh_token: "{{ shajal_google_drive_refresh_token }}"

google_photos_access_token: "{{ shajal_google_photos_access_token }}"
google_photos_refresh_token: "{{ shajal_google_photos_refresh_token }}"

pcloud_access_token: "{{ shajal_pcloud_access_token }}"

su_google_photos_tv_access_token: "{{ sushmoy_google_photos_mytv4kk2_access_token }}"
su_google_photos_tv_refresh_token: "{{ sushmoy_google_photos_mytv4kk2_refresh_token }}"

su2_google_photos_access_token: "{{ sushmoy2_google_photos_access_token }}"
su2_google_photos_refresh_token: "{{ sushmoy2_google_photos_refresh_token }}"

su12_google_photos_access_token: "{{ sushmoy12_google_photos_access_token }}"
su12_google_photos_refresh_token: "{{ sushmoy12_google_photos_refresh_token }}"
