---
- include_tasks: install_rclone.yml
# These are containers that will mount clould storage in local linux machine. Don't need it
# - include_tasks: deploy_google_drive.yml
# - include_tasks: deploy_rclone_pcloud.yml
