---
ssh_directory: "/home/shajal/.ssh/"
ssh_public_key: "{{ ssh_directory }}id_rsa.pub"
ssh_key_path: "{{ ssh_directory }}id_rsa"
ssh_port: 22
shell: /bin/bash
base_storage_path: "/mnt/cache/Apps/Docker"
base_app_storage_path: "/mnt/storage/Apps/CloudData/Docker"

base_local_ssd_storage_path: "/home/shajal/Apps/Docker"

base_db_path: "/mnt/cache/Apps/DatabaseFiles"
my_cloud_nas_storage_path: "/mnt/storage/DataStorage"
my_non_cloud_nas_storage_path: "/mnt/storage/NonCloudDataStorage"
my_cloud_nas_app_storage_path: "/mnt/storage/Apps/CloudData"

matrix_url: "https://matrix.shajalslab.top"
matrix_user_id: "@homelab:matrix.shajalslab.top"
matrix_room_id: "!EeepdmpVgLXnFtyaBd:matrix.shajalslab.top"
matrix_access_token: "{{ matrix_access_token }}"

subdomain: "shajalslab.top"
cloudflare_tunnel_name: "homelab_cloud_tunnel"
pvehomelab_cf_dns_api_token: "{{ CF_DNS_API_TOKEN }}"
pvehomelab_cloudflare_email: "{{ cloudflare_email }}"

