n8n_base_path: "{{ base_app_storage_path }}/n8n"
n8n_files_dir: "{{ n8n_base_path }}/files"

n8n_local_ssd_path: "{{ base_local_ssd_storage_path }}/n8n"
n8n_config_dir: "{{ n8n_local_ssd_path }}/config"
n8n_db_dir: "{{ n8n_local_ssd_path }}/db"
n8n_db_backups_sripts: "{{ n8n_local_ssd_path }}/backups_scripts"

n8n_db_name: "n8n"
n8n_db_user: "{{ vm_username}}"
n8n_db_password: "{{ db_password }}"

n8n_port: "5678"
n8n_domain: "n8n.{{ subdomain }}"
n8n_timezone: "Europe/London"

n8n_encryption_key_local: "{{ n8n_encryption_key }}"

n8n_backup_db: true
n8n_restore_db: false