---
samba_user: "{{ vm_username }}"
samba_password: "{{ vm_username }}"

shares:
  - name: AnannyaCloud
    path: "{{ base_mergerfs_storage_path }}/DataStorage/Anannya/"
    guest_ok: "no"
    public: "no"
    writeable: "yes"
    username: "anannya"
    password: "{{ ana_pass }}"
  - name: Anannya
    path: "{{ base_mergerfs_storage_path }}/NonCloudDataStorage/Anannya/"
    guest_ok: "no"
    public: "no"
    writeable: "yes"
    username: "anannya"
    password: "{{ ana_pass }}"
  - name: SushmoyCloud
    path: "{{ base_mergerfs_storage_path }}/DataStorage/Sushmoy/"
    guest_ok: "no"
    public: "no"
    writeable: "yes"
    username: "sushmoy"
    password: "{{ sush_pass }}"
  - name: Sushmoy
    path: "{{ base_mergerfs_storage_path }}/NonCloudDataStorage/Sushmoy/"
    guest_ok: "no"
    public: "no"
    writeable: "yes"
    username: "sushmoy"
    password: "{{ sush_pass }}"
  - name: ShajalCloud
    path: "{{ base_mergerfs_storage_path }}/DataStorage/Shajal/"
    guest_ok: "no"
    public: "no"
    writeable: "yes"
    username: "shajal"
    password: "{{ vm_password }}"
  - name: Shajal
    path: "{{ base_mergerfs_storage_path }}/NonCloudDataStorage/Shajal/"
    guest_ok: "no"
    public: "no"
    writeable: "yes"
    username: "shajal"
    password: "{{ vm_password }}"
  - name: Media
    path: "{{ base_mergerfs_storage_path }}/NonCloudDataStorage/Media/"
    guest_ok: "yes"
    public: "yes"
    writeable: "yes"
    username: "nobody"
    group: "nogroup"
    password: ""
  - name: Games
    path: "{{ base_mergerfs_storage_path }}/NonCloudDataStorage/Games/"
    guest_ok: "yes"
    public: "yes"
    writeable: "yes"
    username: "nobody"
    group: "nogroup"
    password: ""
