---
ssh_directory: "/home/shajal/.ssh/"
ssh_public_key: "{{ ssh_directory }}id_rsa.pub"
ssh_key_path: "{{ ssh_directory }}id_rsa"
ssh_port: 22
vm_username: "{{ vm_username }}"
vm_password: "{{ vm_password }}"

base_storage_path: "/home/apps"
pveailab_cloudflare_email: "{{ cloudflare_email }}"
pveailab_cf_dns_api_token: "{{ CF_DNS_API_TOKEN }}"

subdomain: "ai.kelovate.online"
cloudflare_tunnel_name: "ailab_cloud_tunnel"
