---
- name: Install MergerFS
  apt:
    name: mergerfs
    state: present

- name: Ensure mount directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ mergerfs_mount_location }}"
    - "{{ mergerfs_mount_location_without_cache }}"

- name: Ensure cache disk is mounted
  command: "findmnt {{ cache_storage }}"
  register: cache_mount_check
  changed_when: false
  failed_when: cache_mount_check.rc != 0

- name: Ensure disks are mounted
  command: "findmnt {{ item }}"
  register: mount_check
  changed_when: false
  failed_when: mount_check.rc != 0
  loop: "{{ data_storage }}"

- name: Set combined data storage.
  set_fact:
    combined_data_storage: "{{ data_storage | join(':') }}"

- name: Unmount if already mounted
  mount:
    path: "{{ item }}"
    state: unmounted
  loop:
    - "{{ mergerfs_mount_location }}"
    - "{{ mergerfs_mount_location_without_cache }}"

- name: Configure Cached Pool (ff policy) with SSD
  mount:
    path: "{{ mergerfs_mount_location }}"
    src: "{{ cache_storage }}:{{ combined_data_storage }}"
    fstype: fuse.mergerfs
    opts: "defaults,allow_other,use_ino,dropcacheonclose=true,cache.files=partial,fsname=mergerfs-cached,category.create=ff"
    state: mounted

- name: Configure Static Pool (epmfs policy) without SSD
  mount:
    path: "{{ mergerfs_mount_location_without_cache }}"
    src: "{{ combined_data_storage }}"
    fstype: fuse.mergerfs
    opts: "defaults,allow_other,use_ino,dropcacheonclose=true,cache.files=partial,fsname=mergerfs-static,category.create=epmfs"
    state: mounted
