---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Check if networks exist
  command: docker network inspect {{ item }}
  register: network_check
  failed_when: network_check.rc != 0
  changed_when: false
  loop: 
    - traefik_proxy

- name: Create Matrix directory
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  loop:
    - "{{ cron_nas_base_path }}"
    - "{{ cron_local_scripts_path }}"
  tags: cronjob

- name: Copy notification script
  template:
    src: templates/matrix_notify.py.j2
    dest: "{{ cron_local_scripts_path }}/matrix_notify.py"
    mode: '0755'
  tags: cronjob

- name: Upsert job block (creates file if missing)
  blockinfile:
    path: "{{ corn_nase_base_crontab_file }}"
    marker: "# {mark} NAME: {{ cron_name }}"
    block: |
      {{ cron_schedule }} ( {{ cron_script_to_run }} 2>&1 ; echo EXIT:\$? ) | python3 /scripts/matrix_notify.py \"{{ notification_message }}\"
    create: true
    insertafter: EOF
    mode: '0644'
    owner: root
    group: root
  tags: cronjob

- name: Deploy Cron Docker Container
  docker_container:
    name: cron_runner
    image: ubuntu:25.10
    hostname: cron_runner
    volumes:
      - "{{ corn_nase_base_crontab_file }}:/cronfiles/cronfile:rw"
      - "{{ cron_local_scripts_path }}:/scripts:ro"
      # - "{{ cron_local_scripts_path }}/matrix_notify.py:/notifier/matrix_notify.py:ro"
    labels:
      com.docker.compose.project: "cron_stack"
      com.docker.compose.service: "cron_runner"
    networks:
      - name: traefik_proxy
    restart_policy: unless-stopped
    state: started
  tags: cronjob

- name: Run script inside Docker container
  docker_container_exec:
    container: cron_runner
    command: /bin/bash -c "{{ lookup('file', script_path) }}"
  register: result
  when: script_path is defined
  tags: cronjob

- name: Display success message
  ansible.builtin.debug:
    msg: "Script {{ script_path }} executed successfully."
  when: 
    - script_path is defined
    - result.rc == 0

- name: Display failure message
  ansible.builtin.debug:
    msg: "Script {{ script_path }} execution failed. Return code: {{ result.rc }}"
  when: 
    - script_path is defined
    - result.rc != 0

- name: Run script inside Docker container
  docker_container_exec:
    container: cron_runner
    command: crontab /cronfiles/cronfile"
  tags: cronjob

- name: Success message for cronjob setup
  debug:
    msg: "Cronjob initiated successfully"
  tags: cronjob
