---
# - name: Ensure Docker service is running and setup user access
#   include_role:
#     name: common
#     tasks_from: setup_docker_user
#   vars:
#     target_user: "{{ docker_user }}"
#   tags: cronjob

- name: Ensure docker networks exist
  community.docker.docker_network:
    name: "{{ network_item }}"
    state: present
  loop:
    - traefik_proxy
  loop_control:
    loop_var: network_item
  tags: cronjob

- name: Get user information
  getent:
    database: passwd
    key: "{{ docker_user }}"
  tags: cronjob

- name: Set UID and GID facts
  set_fact:
    target_uid: "{{ getent_passwd[docker_user][1] }}"
    target_gid: "{{ getent_passwd[docker_user][2] }}"
  tags: cronjob

- name: Create directory
  file:
    path: "{{ directory_item }}"
    state: directory
    owner: "{{ target_uid }}"
    group: "{{ target_gid }}"
    recurse: true
    mode: "0755"
  loop:
    - "{{ cron_nas_base_path }}"
    - "{{ cron_nas_scripts_path }}"
  loop_control:
    loop_var: directory_item
  tags: cronjob

- name: Copy notification script
  template:
    src: templates/matrix_notify.py.j2
    dest: "{{ cron_nas_scripts_path }}/matrix_notify.py"
    owner: "{{ target_uid }}"
    group: "{{ target_gid }}"
    mode: '0755'
  tags: cronjob

- name: Upsert job block (creates file if missing)
  blockinfile:
    path: "{{ cron_nas_base_path }}/custom_cronfile"
    marker: "# {mark} NAME: {{ app_name }}"
    block: |
      {{ cron_schedule }} ( {{ cron_script_to_run }} 2>&1 ; echo EXIT:$? ) | python3 /scripts/matrix_notify.py "{{ notification_message }}"
    create: true
    insertafter: EOF
    mode: '0644'
    owner: "{{ target_uid }}"
    group: "{{ target_gid }}"
  when: no_cron_change is not defined or no_cron_change == false
  tags: cronjob

# - name: Stat docker socket
#   become: true
#   ansible.builtin.stat:
#     path: /var/run/docker.sock
#   register: docker_sock

- name: Deploy Cron Docker Container
  docker_container:
    name: cron_runner
    image: ubuntu:25.10
    hostname: cron_runner
    # user: "{{ target_uid }}:{{ target_gid }}"
    # groups:
    #   - "{{ docker_sock.stat.gid }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ cron_nas_all_apps_path }}:/apps:rw" # Need this to store backups and remove old ones
      - "{{ cron_nas_base_path }}:/etc/cron.d:rw"
      - "{{ cron_nas_scripts_path }}:/scripts:rw"
    command: bash -c "apt-get update && apt-get install -y --no-install-recommends postgresql-client python3 python3-matrix-nio coreutils tzdata ca-certificates docker.io cron && rm -rf /var/lib/apt/lists/* && cron -f"
    labels:
      com.docker.compose.project: "cron_stack"
      com.docker.compose.service: "cron_runner"
    networks:
      - name: traefik_proxy
    restart_policy: unless-stopped
    state: started
  tags: cronjob

- name: Wait until cron is available inside container
  ansible.builtin.shell: |
    docker exec cron_runner pgrep cron
  register: result
  until: result.rc == 0
  retries: 50
  delay: 5
  tags: cronjob

- name: Run crontab inside docker container
  community.docker.docker_container_exec:
    container: cron_runner
    command: crontab /etc/cron.d/custom_cronfile
  when: no_cron_change is not defined or no_cron_change == false
  tags: cronjob

- name: Success message for cronjob setup
  debug:
    msg: "Cronjob container initiated successfully"
  tags: cronjob
