---
nextcloud_data_directory: "{{ my_cloud_nas_storage_path }}/Nextcloud"

nextcloud_base_directory: "{{ base_app_storage_path }}/nextcloud"
nextcloud_config_directory: "{{ nextcloud_base_directory }}/config"

nextcloud_local_ssd_path: "{{ base_local_ssd_storage_path }}/nextcloud"
nextcloud_local_configs_directory: "{{ nextcloud_local_ssd_path }}/configs"
nextcloud_db_data_directory: "{{ nextcloud_local_ssd_path }}/db_data"
nextcloud_backup_scripts: "{{ nextcloud_local_ssd_path }}/backup_scripts"


nextcloud_db_name: "nextcloud_db"
nextcloud_db_user: "{{ vm_username }}"
nextcloud_db_password: "{{ db_password }}"

redis_password: "{{ db_password }}"

nextcloud_domain: "nextcloud.{{ subdomain }}"
nextcloud_domain2: nextcloud.tail41c751.ts.net

nextcloud_backup_db: true
nextcloud_restore_db: false

